# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151012220059 on 2015-10-24 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_test', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
                ('lat', models.IntegerField(default=0)),
                ('long', models.IntegerField(default=0)),
            ],
        ),
    ]
