# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-10-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNF', '0005_auto_20151027_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pet_picture',
            field=models.ImageField(default='/static/LNF/images/chinesecrested.jpg', upload_to='/static/LNF/images/'),
        ),
    ]
