# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-10-27 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LNF', '0006_auto_20151027_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pet_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='post',
            name='breed',
            field=models.CharField(default='Default_value', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='colour',
            field=models.CharField(default='Red', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2015, 10, 27, 18, 50, 40, 221199, tzinfo=utc), verbose_name='date lost/found'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 10, 27, 18, 50, 48, 625488, tzinfo=utc), verbose_name='date last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Default_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
